#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# Your script should only display:
#	username
#	user id
#	Home directory path for the user

file="/etc/passwd"

USERNAME=""
GID=""
HOMEDIR=""
CMD=""
USERID=""
PASS=""
USERINFO=""

while IFS= read -r line
do
	USERNAME="$(echo "$line" | cut -d ":" -f 1)"
	GID="$(echo "$line" | cut -d ":" -f 4)"
	HOMEDIR="$(echo "$line" | cut -d ":" -f 6)"
	CMD="$(echo "$line" | cut -d ":" -f 7)"
	USERID="$(echo "$line" | cut -d ":" -f 3)"
	PASS="$(echo "$line" | cut -d ":" -f 2)"
	USERINFO="$(echo "$line" | cut -d ":" -f 5)"

	echo "The user $USERNAME is part of the $GID gang, lives in $HOMEDIR and rides $CMD. $USERID's place is protected by the passcode $PASS, more info about the user here: $USERINFO"

done < $file
