#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

file=~/hosts.new

echo -e "127.0.0.2\tlocalhost" > $file

echo -e "8.8.8.8\tfacebook.com" >> $file

cp -f $file /etc/hosts
