#!/usr/bin/env bash
# using user "nginx" to handle nginx server
# user nginx must be listening on all active IPs on port 8080

# After creating the 'nginx ' user

# change the default user in nginx conf to 'nginx'
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# change the default port to be 8080
sed -i "s/80/8080/" /etc/nginx/sites-available/default

# change ownership
chown -R nginx:nginx /etc/nginx

chmod 644 /etc/nginx/nginx.conf

pkill apache2

sudo -u nginx -c "service nginx restart"
