#!/usr/bin/env bash
#  a Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user ubuntu.

# Variables

remote_user="ubuntu"
remote_host="34.204.101.226"
private_key_path="~/.ssh/school"

ssh -i "$private_key_path" "$remote_user@$remote_host"
